name: Bug report
description: Report a reproducible problem in MacWiFi
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please include enough detail to reproduce it.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A short description of the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps, in order
      placeholder: |
        1. Open menu bar app
        2. Start connection check
        3. Observe issue...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What happened instead?
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: App version
      description: Release tag or commit hash
      placeholder: v1.2.3 or abc1234

  - type: input
    id: macos
    attributes:
      label: macOS version
      placeholder: macOS 15.3
    validations:
      required: true

  - type: input
    id: xcode
    attributes:
      label: Xcode version (if building from source)
      placeholder: Xcode 16.2

  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Paste relevant logs, error text, or screenshots
      render: shell

