name: Feature request
description: Suggest an improvement to MacWiFi
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion. Focus on user problem first, then proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user problem are you trying to solve?
      placeholder: It is currently hard to...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should the app do?
      placeholder: Add a setting/button/flow that...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternatives or workarounds?

  - type: textarea
    id: scope
    attributes:
      label: Scope and impact
      description: Who benefits and what tradeoffs exist?

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Mockups, screenshots, links, or references

